Repository apify/apify-actor-docker, pull requests merged in 2023-03, with the labels that each got.

#92 feat: add python playwright image
  .github/scripts/prepare-python-image-tags.js
  .github/workflows/release-python-playwright.yaml
  README.md
  python-playwright/.dockerignore
  python-playwright/Dockerfile
  python-playwright/src/__main__.py
  python-playwright/src/main.py
  python-playwright/start_xvfb_and_run_cmd.sh
Labels: t-platform

#93 Update Python base images and release workflows
  .github/workflows/release-python-playwright.yaml
  .github/workflows/release-python.yml
  python-playwright/Dockerfile
  python-playwright/src/__main__.py
  python-playwright/src/main.py
  python/Dockerfile
  python/main.py
  python/src/__main__.py
  python/src/main.py
Labels: t-platform

#96 Add correct default inputs to Python workflows
  .github/workflows/release-python-playwright.yaml
  .github/workflows/release-python-selenium.yaml
  .github/workflows/release-python.yml
Labels: t-platform, adhoc

#97 Update GitHub actions to fix deprecations
  .github/workflows/release-node.yml
  .github/workflows/release-playwright.yml
  .github/workflows/release-puppeteer.yml
  .github/workflows/release-python-playwright.yaml
  .github/workflows/release-python-selenium.yaml
  .github/workflows/release-python.yml
Labels: t-platform, adhoc, debt
