Repository apify/apify-actor-docker, pull requests merged in 2023-10, with the labels that each got.

#111 chore: mark built images as having browsers installed
  node-playwright-chrome/Dockerfile
  node-playwright-firefox/Dockerfile
  node-playwright-webkit/Dockerfile
  node-playwright/Dockerfile
  node-puppeteer-chrome/Dockerfile
Labels: adhoc, t-tooling

#114 Fix Chromedriver compatibility issue in Python-Selenium
  python-selenium/Dockerfile
Labels: t-tooling

#115 Fix invalid label key (Description -> description)
  node-playwright-chrome/Dockerfile
  node-playwright-firefox/Dockerfile
  node-playwright-webkit/Dockerfile
  node-playwright/Dockerfile
  node-puppeteer-chrome/Dockerfile
  node/Dockerfile
  python-playwright/Dockerfile
  python-selenium/Dockerfile
  python/Dockerfile
Labels: adhoc, debt, t-tooling

#112 Add support for Python 3.12
  .github/workflows/release-python-playwright.yaml
  .github/workflows/release-python-selenium.yaml
  .github/workflows/release-python.yaml
Labels: t-tooling

#117 Size reduction of the Python Docker images
  .github/workflows/release-python-playwright.yaml
  .github/workflows/release-python-selenium.yaml
  python-playwright/Dockerfile
  python-selenium/Dockerfile
  python/Dockerfile
Labels: t-tooling
